### ISSUE TITLE
Edit the title and nav-bar

### ISSUE THREAD

**Issue by shovan-mondal** [Mondalgithub/hololearn#3]
![Screenshot_20200802-153240_Chrome](https://user-images.githubusercontent.com/63331895/89120647-9881fe00-d4d5-11ea-9ab8-f83d1a1f2c52.jpg)

**Comment by Anik-08** [comment]
What's the issue is it regarding the line "View your Physics DPP here."?

**Comment by shovan-mondal** [comment]
The title is touching the upper line. Also the nav-bar should be lowered. We can clear this error on working on the responsive side of the template.

**Comment by Mondalgithub** [comment]
We can clear this error on working on the responsive side of the template.

**Comment by Anik-tech8** [comment]
Ok it is fine with me.

**Comment by shovan-mondal** [comment]
Debugging. Update in process

**Comment by shovan-mondal** [comment]
Debugged successfully.
