### ISSUE TITLE
Pictures are not in centre in android view.

### ISSUE THREAD

**Issue by shovan-mondal** [Mondalgithub/hololearn#5]
![Screenshot_20200802-155625_Chrome](https://user-images.githubusercontent.com/63331895/89121019-dfbdbe00-d4d8-11ea-88a5-8cea0caf5f87.jpg)

**Comment by Anik-08** [comment]
The problem doesn't occur when it is downloaded and seen in laptop.
![logo](https://user-images.githubusercontent.com/63413283/89121303-5d82c900-d4db-11ea-895b-2fa43bc9cff6.png)

**Comment by shovan-mondal** [comment]
Ok. I will recheck why this issue is occurring. I think it is because of over-codes on a single class. I will try deleting some unwanted codes.

**Comment by shovan-mondal** [comment]
The error is cleared now.
