### ISSUE TITLE
On selecting DPP from membership page it shows file not found.

### ISSUE THREAD

**Issue by Anik-08** [Mondalgithub/hololearn#7]
[
![image](https://user-images.githubusercontent.com/63413283/89121544-670d3080-d4dd-11ea-9373-1946418acbe0.png)
](url)

**Comment by shovan-mondal** [comment]
@Anik-tech8 Pls do not check the buttons after cloning my website. It will give error. Pls visit hololearn.cf from there all the buttons work.
