### ISSUE TITLE
Text missing

### ISSUE THREAD

**Issue by Anik-08** [Mondalgithub/hololearn#9]
The exercises names are missing when it is seen in android view.

![Screenshot_2020-08-03-19-40-05](https://user-images.githubusercontent.com/63413283/89192299-d3616000-d5c1-11ea-89b7-134cd09c6228.png)

**Comment by Mondalgithub** [comment]
debugging..

**Comment by shovan-mondal** [comment]
**Latest commit:** The issue doesn't occur in my cloned webpage. It is occurring only in the website. Another thing to note is that in website till 401px  it displays all the text but as soon as it reaches 400px the text go missing.


![error](https://user-images.githubusercontent.com/63331895/89299140-e2a8e200-d683-11ea-8350-fd6d17dd471f.png)



This is my cloned webpage at 400px(above)
-text is visible


![error3](https://user-images.githubusercontent.com/63331895/89298920-9bbaec80-d683-11ea-8da6-ff5f41711a66.png)


This is the website at 400px.(above)
 -text go missing.

### I have no idea why this happens!

**Comment by shovan-mondal** [comment]
Fetched the error. The <p1> was creating this issue. Debugging now.

**Comment by shovan-mondal** [comment]
**Debugged successfully.**
